___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [186]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [187]:
my_list = np.array([5,10,15,20,25])
my_list

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [188]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [189]:
x = np.ones((4,4), dtype=int)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [190]:
x[x>0] = 7
x

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [191]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [192]:
new_list = np.array(range(8))
new_list

array([0, 1, 2, 3, 4, 5, 6, 7])

#### 7. Create an array of even integers from 2 to 16 

In [193]:
np.arange(2,17)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [194]:
a = np.arange(0,25)
new_a = a.reshape(5,5)
new_a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [195]:
a = np.linspace(start=[0,5,10,15,20], stop=[4,9,14,19,24], num=5, dtype=int)
a

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

#### 10. Create 5 random number with numpy

In [196]:
np.random.rand(5)

array([0.84447896, 0.57163806, 0.10461481, 0.33221838, 0.21687002])

#### 11. Create random normal distributed 5x5 array

In [197]:
np.random.rand(5,5)

array([[0.92618322, 0.9193353 , 0.25511401, 0.78950097, 0.45743758],
       [0.10404368, 0.27778288, 0.34089725, 0.65273175, 0.09866158],
       [0.89164388, 0.44231038, 0.42925327, 0.57848626, 0.98124719],
       [0.25467031, 0.46006009, 0.31549347, 0.95944901, 0.38657845],
       [0.48161039, 0.41995497, 0.33125051, 0.07227271, 0.31807878]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [198]:
np.random.randint(20,50, size=(3,4))

array([[37, 22, 23, 40],
       [41, 47, 30, 44],
       [40, 35, 20, 22]])

#### 13. Reshape the array below with shape 6x8

In [199]:
ranarr = np.array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [200]:
ranarr

array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [201]:
ranarr.reshape(6,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [202]:
#reshape with -1
ranarr.reshape(-1,12)

array([[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8],
       [44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35],
       [45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection


In [203]:
#Create array below
mat = np.arange(1, 17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [204]:
a = np.array([6,7,10,11]).reshape(2,2)
a

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [205]:
a = np.array([ 1,  5,  9, 13])
a

array([ 1,  5,  9, 13])

In [206]:
a[0]

1

#### 16. Get the values in 2nd row for every 2 step.

In [207]:
mat[1][::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [208]:
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [209]:
mat[[0,1,2,3],2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [210]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [211]:
mat[1::2,0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [212]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [213]:
x = mat[mat<10]
x

array([1, 2, 4, 5, 6, 8, 9])

In [214]:
y = mat[mat>12]
y

array([77, 77, 77, 13, 14, 77, 16])

In [215]:
a = x+y
a

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [216]:
np.std(a)

29.700546274093877

#### 22. Get the sum of second column from array above

In [217]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [218]:
mat.sum(axis=0)[1]

32

#### 23. Get the median,mean and std of 3rd row from array above

In [219]:
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [220]:
mat[2]

array([ 9, 10, 11, 12])

In [221]:
#median
np.median(mat[2], axis=0)

10.5

In [222]:
#mean
np.mean(mat[2], axis=0)

10.5

In [223]:
#std
np.std(mat[2], axis=0)

1.118033988749895

# Pandas Section

In [224]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [225]:
sal=pd.read_csv('Salaries.csv')

In [226]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [227]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [228]:
sal.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year value are there**

In [229]:
sal.groupby("Year").Id.count().sort_index(ascending=False)

Year
2014    38123
2013    37606
2012    36766
2011    36159
Name: Id, dtype: int64

**Print out max and avg Totalpay**

In [230]:
#max
sal.TotalPay.max()

567595.43

In [231]:
#avg
sal.TotalPay.mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [232]:
(sal.TotalPay>sal.TotalPay.mean()).sum()

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [233]:
sal.loc[sal["EmployeeName"] == "ALBERT PARDINI"].TotalPayBenefits

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [234]:
sal.loc[sal["TotalPayBenefits"] == min(sal.TotalPayBenefits)].EmployeeName

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [235]:
sal.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [236]:
sal.groupby("JobTitle").Id.count().sort_values(ascending=True).head(3)

JobTitle
ZOO CURATOR                               1
DIRECTOR, INFORMATION TECHNOLOGY GROUP    1
DIRECTOR, HUMAN RESOURCES                 1
Name: Id, dtype: int64

**How many people earned more than avg in 2012**

In [237]:
a = sal.loc[sal["Year"] == 2012].TotalPayBenefits
b = sal.TotalPayBenefits.mean()
(a > b).sum()

20366

**How many people have the word Manager in their job title?**

In [238]:
#use apply function here
sal.JobTitle.str.findall("Manager").apply(len).sum()

3080

In [239]:
sal.JobTitle.str.contains("Manager").sum()

3080

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [240]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [241]:
sal_new = sal.iloc[ : ][["Id","EmployeeName","JobTitle","TotalPay","TotalPayBenefits"]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [242]:
sal_new = sal_new.loc[ :  ,"EmployeeName":"TotalPayBenefits"]
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [243]:
a = sal.loc[sal["TotalPayBenefits"] > sal["TotalPayBenefits"].min()]
b = sal.loc[sal["TotalPayBenefits"] < sal["TotalPayBenefits"].mean()]

In [244]:
a

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148648  148649        Leon Walker   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148648                                       Custodian       0.00   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148648         0.00       0.00       0.0       0.00              0.00  2014   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148648    NaN  San Francisco     NaN  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  

[148653 rows x 13 columns]

In [245]:
b

Id    EmployeeName                    JobTitle   BasePay  \
10806    10807         KWE LEE         AUTOMOTIVE MECHANIC  72198.10   
10807    10808  MIGUEL CARO JR         STATIONARY ENGINEER  72420.69   
10808    10809   JOANNE MORRIS            REGISTERED NURSE  91672.69   
10809    10810   LAYLA WELBORN               SPECIAL NURSE  80683.54   
10810    10811         LE BANH            TRANSIT OPERATOR  67349.30   
...        ...             ...                         ...       ...   
148649  148650   Roy I Tillery                   Custodian      0.00   
148650  148651    Not provided                Not provided       NaN   
148651  148652    Not provided                Not provided       NaN   
148652  148653    Not provided                Not provided       NaN   
148653  148654       Joe Lopez  Counselor, Log Cabin Ranch      0.00   

        OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
10806       6017.76  15475.29       NaN  93691.15          93691.15  2011   
10807       2665.79  18596.26       NaN  93682.74          93682.74  2011   
10808          0.00   2007.84       NaN  93680.53          93680.53  2011   
10809       8809.03   4184.31       NaN  93676.88          93676.88  2011   
10810      23507.62   2818.47       NaN  93675.39          93675.39  2011   
...             ...       ...       ...       ...               ...   ...   
148649         0.00      0.00       0.0      0.00              0.00  2014   
148650          NaN       NaN       NaN      0.00              0.00  2014   
148651          NaN       NaN       NaN      0.00              0.00  2014   
148652          NaN       NaN       NaN      0.00              0.00  2014   
148653         0.00   -618.13       0.0   -618.13           -618.13  2014   

        Notes         Agency  Status  
10806     NaN  San Francisco     NaN  
10807     NaN  San Francisco     NaN  
10808     NaN  San Francisco     NaN  
10809     NaN  San Francisco     NaN  
10810     NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[75650 rows x 13 columns]

In [246]:
x = pd.merge(a, b, left_index=True, right_index=True)
x.EmployeeName_x

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName_x, Length: 75649, dtype: object