___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 3</p><h1>

# Pandas Series

In [1]:
import numpy as np  # numpy'ı import ettik
import pandas as pd  # pandası'ı import ettik

## Creating a Pandas Series

pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)

One-dimensional ndarray with axis labels (including time series).

In [2]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

### **Using Lists**

In [3]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series([10, 20, 30])

0    10
1    20
2    30
dtype: int64

### **Using NumPy Arrays**

In [6]:
arr  # Üstte tanımlamıştık

array([10, 20, 30])

In [7]:
pd.Series(data=arr, index=labels)  # İndexleri değiştirdik

a    10
b    20
c    30
dtype: int32

### **Using Dictionary**

In [8]:
d

{'a': 10, 'b': 20, 'c': 30}

In [9]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(d, index=["q","c","y"])  # Dictionary kullanıyorsak indexleme yapmamaşıyız. Dictionary'deki keyler zaten index
# NaN'ın default değeri floattır. Bu nedenle 30.0 getirdi. Yalnızca bunu döndürmesinin nedeni sadece c için eşleşen bir değr bulmasıdır.

q     NaN
c    30.0
y     NaN
dtype: float64

### Using Scalar Value

In [11]:
pd.Series(data="Ahmet")

0    Ahmet
dtype: object

In [12]:
pd.Series(data="Ahmet", index=range(1,5))

1    Ahmet
2    Ahmet
3    Ahmet
4    Ahmet
dtype: object

### Data in a Series

A pandas Series can hold a variety of object types:

{} or set()

In [13]:
pd.Series([set, list, dict])

0     <class 'set'>
1    <class 'list'>
2    <class 'dict'>
dtype: object

In [14]:
pd.Series([set, list, dict])[0]([2,5,7,5,8,2])

{2, 5, 7, 8}

In [15]:
pd.Series([set, list, dict])[2]([('sape', 4139), ('guido', 4127), ('jack', 4098)])  # Dictionary için örnek

{'sape': 4139, 'guido': 4127, 'jack': 4098}

In [16]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [17]:
pd.Series([sum,print,len])[0]([3,5,7])

15

In [18]:
mix_data = ['Aziz', 2, True]

In [19]:
ser = pd.Series(mix_data)
ser

0    Aziz
1       2
2    True
dtype: object

In [20]:
ser.dtype

dtype('O')

In [21]:
type(ser)

pandas.core.series.Series

In [22]:
type(ser[2])  # Serideki 2. indexin tipi

bool

In [23]:
arr = np.array(mix_data)
arr

array(['Aziz', '2', 'True'], dtype='<U11')

In [24]:
type(arr[2])  # Serideki her datanın tipini mmuhafaza etti. Arrayde değiştirdi!!!

numpy.str_

### Basic Attributes of Series

In [25]:
ser = pd.Series(np.random.randint(0, 100, 7))
ser

0     7
1    55
2    42
3    14
4    45
5     7
6    15
dtype: int32

In [26]:
ser.dtype

dtype('int32')

In [27]:
type(ser)

pandas.core.series.Series

In [28]:
ser.shape

(7,)

In [29]:
ser.size

7

In [30]:
len(ser)

7

In [31]:
ser.ndim  # 1 boyutlu

1

In [32]:
ser.index

RangeIndex(start=0, stop=7, step=1)

In [33]:
list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

In [34]:
for i in ser.index:
    print(i)

0
1
2
3
4
5
6


In [35]:
ser.keys()  

RangeIndex(start=0, stop=7, step=1)

In [36]:
ser.values  # Değerleri array olarak döndürür

array([ 7, 55, 42, 14, 45,  7, 15])

In [37]:
ser.items

<bound method Series.items of 0     7
1    55
2    42
3    14
4    45
5     7
6    15
dtype: int32>

In [38]:
ser.items()

In [39]:
list(ser.items())

[(0, 7), (1, 55), (2, 42), (3, 14), (4, 45), (5, 7), (6, 15)]

In [40]:
for index, value in ser.items():
    print(f"index: {index}, value: {value}")

index: 0, value: 7
index: 1, value: 55
index: 2, value: 42
index: 3, value: 14
index: 4, value: 45
index: 5, value: 7
index: 6, value: 15


In [41]:
ser = pd.Series(data = np.random.randint(0,25,10), index = [i for i in "cbaefdgihj"])
ser

c    13
b    10
a     5
e     0
f     8
d    24
g    12
i     0
h    20
j     0
dtype: int32

In [42]:
ser.head()  # Parantez içine kaç yazarsak o kadar sayı getirir. Default'u 5'tir.

c    13
b    10
a     5
e     0
f     8
dtype: int32

In [43]:
ser.tail()

d    24
g    12
i     0
h    20
j     0
dtype: int32

In [44]:
ser.sample()  # Datanın herhangi bir yerinden satırlar getirir.

i    0
dtype: int32

In [45]:
ser.sample(3) 

i     0
e     0
d    24
dtype: int32

In [46]:
ser.sort_index(ascending=True)  # İndex'i sıraladık

a     5
b    10
c    13
d    24
e     0
f     8
g    12
h    20
i     0
j     0
dtype: int32

In [47]:
ser.sort_values(ascending=False)  # Değerleri azalana göre sıralattık

d    24
h    20
c    13
g    12
b    10
f     8
a     5
e     0
i     0
j     0
dtype: int32

In [48]:
ser

c    13
b    10
a     5
e     0
f     8
d    24
g    12
i     0
h    20
j     0
dtype: int32

In [49]:
ser.isin([23,1])  # Girdiğimiz değerler varsa true, yoksa false döndürür

c    False
b    False
a    False
e    False
f    False
d    False
g    False
i    False
h    False
j    False
dtype: bool

In [50]:
pd.Series([i for i in "clarusway"])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [51]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [52]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [53]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [54]:
ser1.sort_index()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [55]:
ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
dtype: int64

In [56]:
ser1[1]

2

In [57]:
ser1["Germany"]

2

In [58]:
ser1.Germany  # string ifadeleri bu şekilde de yazabiliriz (çok tavsiye edilmez)

2

In [ ]:
ser1.1  # Hata verir

In [60]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [61]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [62]:
ser1 + ser2  # Eğer her ikisinde de aynı key varsa toplar yoksa NaN döndürür

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [63]:
ser3 = pd.Series(data = ["a", "b", "c", "d"])
ser3

0    a
1    b
2    c
3    d
dtype: object

In [64]:
ser3[0]

'a'

In [65]:
ser3[:2]

0    a
1    b
dtype: object

In [66]:
ser3[::-1]  # Tersten yazdırır

3    d
2    c
1    b
0    a
dtype: object

### pandas_series[index] | pandas_series[[indices, indices...]]

In [67]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [68]:
panser[["terry", "orion"]]  # Dataframe'lerde sütunları çağırmaya benziyor

terry    121
orion    150
dtype: int64

In [69]:
panser["terry" : "orion"]  # İsimlerle çağırıyosak yazdığımız isimlerin ikisi de dahil olur. İndex şeklinde sayılarla çağırırsam sonuncu sayı dahil olmaz

terry      121
micheal    200
orion      150
dtype: int64

In [70]:
panser[0:3]  # İsimlerle çağırıyosak yazdığımız isimlerin ikisi de dahil olur. İndex şeklinde sayılarla çağırırsam sonuncu sayı dahil olmaz

terry      121
micheal    200
orion      150
dtype: int64

### Recap for Several Selecting Attributes

In [71]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [72]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [73]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [74]:
panser.values

array([121, 200, 150,  99], dtype=int64)

In [75]:
panser.item  # Güzel bir formatta döndürmüyor

<bound method IndexOpsMixin.item of terry      121
micheal    200
orion      150
jason       99
dtype: int64>

In [76]:
panser.items()  # Base object döndürür

In [77]:
for index, value in panser.items():
    print(index, value)

terry 121
micheal 200
orion 150
jason 99


In [78]:
"terry" in panser  # panser içinde terry var mı yok mu'nun cevaını döndürür

True

In [79]:
"bob" in panser

False

In [80]:
200 in panser.values  # Value sorgularken bu şekilde yazmamız lazım. Yoksa algılamaz

True

In [81]:
panser.isin([200,150])

terry      False
micheal     True
orion       True
jason      False
dtype: bool

In [82]:
panser[panser>100]

terry      121
micheal    200
orion      150
dtype: int64