In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a[0]

1

In [4]:
a[2]

3

In [15]:
import numpy as np

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
l = range(5)

In [26]:
l[0]

0

In [27]:
l[2]

2

In [28]:
l[5]  # range'e 5 dahil olmadığından hata verir

IndexError: range object index out of range

In [30]:
np.arange(1, 5)  # 1 ile 5 arasında liste oluşturdu

array([1, 2, 3, 4])

In [31]:
np.arange(1, 5, 2)  # 1 ile 5 arasında 2 aralıkla sayılar oluşturdu

array([1, 3])

In [32]:
np.linspace(1, 5, 10)  # 1 ile 5 arasında 10 eşit aralıklı sayıyı döndürür

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [86]:
np.linspace(1, 15, 8)  # 1 ile 15 arasında 8 eşit aralıklı sayıyı döndürür

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15.])

In [35]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
a.shape  # 3 rows, 2 columns

(3, 2)

In [38]:
a.reshape(2, 3)  # 2 rows, 3 colums olarak güncelledi

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a.ravel()  # 1 dimensional array haline getirir (orijinalini değiştirmez)

array([1, 2, 3, 4, 5, 6])

In [40]:
a  # orijinal hali değişmez

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
a.min()

1

In [42]:
a.max()

6

In [43]:
a.sum()

21

In [44]:
a.sum(axis=0)  # 1+3+5, 2+4+6

array([ 9, 12])

In [46]:
a.sum(axis=1)  # 1+2, 3+4, 5+6

array([ 3,  7, 11])

In [50]:
np.sqrt(a)  # Karekök alır

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [51]:
np.std(a)  # Sayıların standart sapmasını alır

1.707825127659933

In [52]:
x = np.array([[1,2], [3,4]])

In [56]:
y = np.array([[5,6], [7,8]])

In [54]:
x

array([[1, 2],
       [3, 4]])

In [57]:
y

array([[5, 6],
       [7, 8]])

In [58]:
x+y

array([[ 6,  8],
       [10, 12]])

In [60]:
x*y

array([[ 5, 12],
       [21, 32]])

In [61]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [62]:
x.dot(y)  # Matris alır

array([[19, 22],
       [43, 50]])

In [63]:
a = np.array([5,6,9])  # 1 dimensional array

In [64]:
a[0]

5

In [65]:
a = np.array([[1,2], [3,4], [5,6]])  # 2 dimensional array

In [67]:
a[1]

array([3, 4])

In [68]:
a.ndim  # ndim ile oluşturulan arrayin kaç dimensional olduğunu görürürüz

2

In [69]:
a.itemsize  # a'nın 4 bites olduğunu gösterir

4

In [71]:
a.dtype  # data type of this array

dtype('int32')

In [76]:
a=np.array([[1,2], [3,4], [5,6]], dtype=np.float64)  # Float hale getirdik

In [77]:
a.itemsize

8

In [78]:
a  

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [79]:
a.size  # Total number of elements

6

In [84]:
a=np.array([[1,2], [3,4], [5,6]], dtype=complex)  

In [85]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [90]:
np.random.randint(1, 10)

7

In [100]:
a=np.array([6,7,8])

In [101]:
a[0:2]

array([6, 7])

In [102]:
a[-1]

8

In [103]:
a=np.array([[6,7,8], [1,2,3], [9,3,2]])

In [104]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [105]:
a[1,2]  # 1. satır 2. sütun (satır ve sütunları saymaya 0'dan başlıyoruz)

3

In [111]:
a[0:2, 2]  # Virgül satır ve sütun değerlerini ayırıyor. Yani 0:2 satır için (6,7,8 ve 1,2,3 satırları), 2 sütun için (8,3).

array([8, 3])

In [110]:
a[1:2, 1:2]

array([[2]])

In [109]:
a[-1]  # Last element

array([9, 3, 2])

In [112]:
a[-1, 0:2]

array([9, 3])

In [113]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [114]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [116]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [117]:
a=np.arange(6).reshape(3,2)

In [118]:
b=np.arange(6,12).reshape(3,2)

In [119]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [121]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [123]:
np.vstack((a, b))  # vertical stack

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [125]:
np.hstack((a,b))  # horizontal stack

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [128]:
x=np.arange(30).reshape(2,15)

In [129]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [136]:
np.hsplit(x, 3)  # Horizontal split

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [137]:
x  

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [133]:
result = np.hsplit(x,3) 

In [134]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [138]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [139]:
result = np.vsplit(a, 2)  # Vertical split

In [141]:
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [140]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [142]:
result[-1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [149]:
m=np.arange(12).reshape(3,4)

In [150]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [151]:
n = m > 4

In [152]:
n

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [153]:
m[n]  # True olan yerlerdeki değerleri çektik

array([ 5,  6,  7,  8,  9, 10, 11])

In [157]:
m[n] = -1  # 4'den büyük olan yani true olan değerlerin yerine -1 yazdırdık

In [158]:
m

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [159]:
arr = np.arange(1,8)

In [160]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [161]:
arr[arr>4]

array([5, 6, 7])

In [163]:
a = np.array([1,2,3,4])

In [165]:
a

array([1, 2, 3, 4])

In [166]:
a+2

array([3, 4, 5, 6])

In [167]:
a-2

array([-1,  0,  1,  2])

In [168]:
a*2

array([2, 4, 6, 8])

In [169]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [170]:
a += 2  # (a=a+2)
a

array([3, 4, 5, 6])

In [174]:
a

array([3, 4, 5, 6])

In [172]:
b = np.array([1,0,1,0])
a+b

array([4, 4, 6, 6])

In [173]:
a**2

array([ 9, 16, 25, 36], dtype=int32)

In [176]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [178]:
arr = np.arange(1,37)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [179]:
arr.shape

(36,)